### ISSUE TITLE
Proteção de senha a partir de hash

### ISSUE THREAD

**Issue by diogomene15** [diogomene15/TrabalhoFinal-GCS#1]
O projeto produzido possui alguns contextos em que o usuário da aplicação necessita estar autenticado. Para isso, ao iniciar a aplicação o usuário é direcionado para uma tela de login ( [`LoginFragment.java`](https://github.com/diogomene15/TrabalhoFinal-GCS/blob/main/app/src/main/java/com/example/karta/activities/LoginFragment.java) ). Nela, a partir das informações de `Email` e `Senha`, o usuário é capaz de acessar a conta criada anteriormente. Caso não possua uma conta, o usuário, acessando a tela de cadastros, é capaz de realizar a inserção de suas informações de `Nome`, `Email` e `Senha`, criando uma conta válida para acessar a aplicação.

Ao realizar uma revisão do funcionamento das funções e telas responsáveis pelo fluxo de criação de contas e autenticação de usuários existentes, foi possível verificar que não existem funcionalidades relacionadas ao mascaramento  das senhas. Ao salvar as senhas como *plain-text* (armazenando-as da mesma forma como foram escritas pelo usuário, sem qualquer tipo de criptografia), cria-se uma possível brecha de segurança das informações dos usuários, visto que as senhas são facilmente coletáveis e observáveis, tornando-as vulneráveis a olhares indiscretos e comprometendo a confidencialidade dos dados.

Para resolver esse problema, proponho a implementação das seguintes medidas:

- Criptografia de Senhas: Adicionar uma camada de criptografia para as senhas, onde, antes de serem armazenadas, deve ocorrer um processo de criptografia, a partir de, preferencialmente, métodos de criptografia não reversíveis (hashing).
- Validação de Senhas: Implementar uma validação mais robusta para senhas, a partir de métodos de comparação de hashing. Dessa forma, o processo de autenticação não será prejudicado pelo fato de que a senha não pode ser revertida a seu estado original.
Essas alterações devem ser realizadas no arquivo [LoginFragment.java](https://github.com/diogomene15/TrabalhoFinal-GCS/blob/main/app/src/main/java/com/example/karta/activities/LoginFragment.java) e em demais componentes relacionados ao fluxo de autenticação (como na tela de cadastro e tela de edição de informações de usuário); ou serem concentradas nas classes `Usuario` e `UsuarioDAO`.

Recomendo envolver a equipe de desenvolvimento (incluindo responsáveis por arquitetura do software) para discutir essas mudanças e obter feedback sobre a melhor forma de implementá-las. No caso de mudanças arquiteturais significantes serem requeridas, julgo de extrema importância o envolvimento da equipe de requisitos, além da formalização de decisões por meio de architectural decision records (ADRs).

**Comment by JoaoPKarpinski** [comment]
Após discutir a questão com @luishscarvalho, chegamos à conclusão de que sem a provisão mínima de privacidade do usuário, como a criptografia de sua senha, não podemos avançar no projeto. Isso é fundamental demais. Poderia mudar essa prioridade para p5, @diogomene15, para alocarmos todos os esforços possíveis para esta issue prioritariamente?

**Comment by JoaoPKarpinski** [comment]
Após discutir a questão com @luishscarvalho, chegamos à conclusão de que sem a provisão mínima de privacidade do usuário, como a criptografia de sua senha, não podemos avançar no projeto. Isso é fundamental demais. Poderia mudar essa prioridade para p5, @diogomene15, para alocarmos todos os esforços possíveis para esta issue prioritariamente?

**Comment by luishscarvalho** [comment]
@JoaoPKarpinski, concordo é fundamental priorizarmos a implementação de criptografia para as senhas no projeto, visando proteger adequadamente as informações dos usuários contra possíveis vulnerabilidades. Essa medida não apenas fortalecerá a segurança, mas também garantirá a confidencialidade dos dados sensíveis armazenados.
