### ISSUE TITLE
Ajustar alinhamento de campos na tela de cadastro de endereços

### ISSUE THREAD

**Issue by JoaoPKarpinski** [diogomene15/TrabalhoFinal-GCS#12]
Foi reportado por um dos QAs que os itens da tela de endereço estão desalinhados e precisam ser ajustados. O report incluiu a seguinte evidência: 
![cadastro_endereco_mal_alinhado](https://github.com/diogomene15/TrabalhoFinal-GCS/assets/111706019/612004a2-6859-4a5b-914c-30b1c938ffb7)
O problema deve estar, baseado na arquitetura do projeto, no arquivo xml "cadastro_endereco_fragment", que pode estar com a horizontal bias dos itens com valores diferentes, visto que os valores de ConstraintLayout estão iguais. 
@diogomene15, pode dar uma olhada neste item, para corrigir o comportamento, caso a suspeita esteja correta, ou propôr uma solução?

**Comment by diogomene15** [comment]
@JoaoPKarpinski. Realizando a revisão do problema, parece, de fato, ser um simples problema de configuração no arquivo `cadastro_endereco_fragment`.

Estarei realizando as alterações necessárias para solução do problema encontrado. Em breve submeto PR
