### ISSUE TITLE
Remover menus das telas de login e cadastro

### ISSUE THREAD

**Issue by JoaoPKarpinski** [diogomene15/TrabalhoFinal-GCS#6]
Ao entrar no aplicativo, temos as opções de login e cadastro, que devem ser realizadas antes de mais nada. Entretanto, há um menu que mostra as possibilidades de "Editar usuário" e "Listar usuários", funcionalidades que só podem ser realizadas após o login ou cadastro. Portanto, a PO solicitou que o menu fosse removido dessas telas, para não induzir o usuário à uma expectativa de utilização desses recursos em um momento no qual eles não podem ser utilizados. Uma sugestão seria utilizar o método setHasOptionsMenu(), da classe Fragment, tendo em vista que as telas são fragmentos. @diogomene15, por ter familiaridade com essas telas, acredito que a alocação de seus esforços para esta issue seria uma boa decisão. 
Segue screenshot do estado atual da tela de cadastro, ao tentar utilizar as funcionalidades do menu:
![karta_cadasrto](https://github.com/diogomene15/TrabalhoFinal-GCS/assets/111706019/1a2b226e-5e3e-47ef-adba-59dd2d7d8bf6)

**Comment by diogomene15** [comment]
@JoaoPKarpinski , conforme conversado em reunião de alinhamento, o menu não pode ser completamente removido, pois deverão ser adicionadas novas funcionalidades em releases futuras, que serão apresentadas no caso do usuário não estar logado.

Uma das funcionalidades, como mencionado pela @JosephineCarter, durante reunião após alinhamento com stakeholders, será a edição de usuários anônimos.

Dessa forma, essa issue, em seu estado atual, não deverá ser implementada (won't fix)

@JoaoPKarpinski, para correção adequada, favor especificar melhor quais partes devem ser alteradas do menu, e se em alguma tela específica, de fato, não deverá ser apresentada - mesmo com alinhamentos citados anteriormente.

**Comment by luishscarvalho** [comment]
@diogomene15 e @JoaoPKarpinski, favor verifiquem possibilidade de remoção do menu, conforme indicado inicialmente pelo @JoaoPKarpinski, e alteração de acesso de usuários anônimos, e demais funcionalidades que seriam acessíveis por usuários não autenticados no menu, para outras localidades.
Em alinhamento com a equipe de UX/UI, a mesma requisição foi feita. Acredito que com um alinhamento mais adequado com os stakeholders podemos atender essa issue, e atender demais demandas de funcionalidades (futuras) a partir de outros meios. Oferecendo, assim, uma experiência mais intuitiva do usuário (conforme comentários da equipe responsável pelo UX)
